### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by TaiSakuma** [alphatwirl/atpbar#4]
`EOFError` occured once in Python 3.6

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/users/ts14043/.conda/envs/ts14043_201903_01_py3_root6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/storage/ts14043/work/cms/c160307_bdphi/c160406_roc/bdphi-scripts/external/atpbar/atpbar/pickup.py", line 22, in run
    self._run_until_the_end_order_arrives()
  File "/storage/ts14043/work/cms/c160307_bdphi/c160406_roc/bdphi-scripts/external/atpbar/atpbar/pickup.py", line 29, in _run_until_the_end_order_arrives
    report = self.queue.get()
  File "/users/ts14043/.conda/envs/ts14043_201903_01_py3_root6/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/users/ts14043/.conda/envs/ts14043_201903_01_py3_root6/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/users/ts14043/.conda/envs/ts14043_201903_01_py3_root6/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/users/ts14043/.conda/envs/ts14043_201903_01_py3_root6/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFErrorn
```

The cause of the error appears to be the same as what is described in the [stackoverflow](https://stackoverflow.com/questions/49209385/eof-error-at-program-exit-using-multiprocessing-queue-and-thread).

**Comment by TaiSakuma** [comment]
This problem is actually quite easy to reproduce

```
ts14043@soolin$ python
Python 3.6.7 | packaged by conda-forge | (default, Feb 20 2019, 02:51:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import atpbar
>>> for i in atpbar.atpbar(range(10)): pass
... 
 100.00% :::::::::::::::::::::::::::::::::::::::: |       10 /       10 |:  range(0, 10)                     
>>> 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/users/ts14043/.conda/envs/ts14043_201903_01_py3_root6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/storage/ts14043/work/cms/c160307_bdphi/c160406_roc/bdphi-scripts/external/atpbar/atpbar/pickup.py", line 22, in run
    self._run_until_the_end_order_arrives()
  File "/storage/ts14043/work/cms/c160307_bdphi/c160406_roc/bdphi-scripts/external/atpbar/atpbar/pickup.py", line 29, in _run_until_the_end_order_arrives
    report = self.queue.get()
  File "/users/ts14043/.conda/envs/ts14043_201903_01_py3_root6/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/users/ts14043/.conda/envs/ts14043_201903_01_py3_root6/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/users/ts14043/.conda/envs/ts14043_201903_01_py3_root6/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/users/ts14043/.conda/envs/ts14043_201903_01_py3_root6/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

The error always happens in this environment on soolin.

The error doesn't happen in Python 3 in macOS.

**Comment by TaiSakuma** [comment]
In fact, the error doesn't happen if `multiprocessing.queues` is imported before `atpbar` is imported.

```
ts14043@soolin$ python
Python 3.6.7 | packaged by conda-forge | (default, Feb 20 2019, 02:51:38) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import multiprocessing.queues
>>> import atpbar
>>> for i in atpbar.atpbar(range(10)): pass
... 
 100.00% :::::::::::::::::::::::::::::::::::::::: |       10 /       10 |:  range(0, 10)                     
>>> 
```

**Comment by TaiSakuma** [comment]
- added a test for this problem https://github.com/alphatwirl/atpbar/commit/2bc25cb18befb90e740db7015f472dc2e7b70f1f
- however, this test fails only on soolin. It doesn't faile on macOS or [travis-ci](https://travis-ci.org/alphatwirl/atpbar/builds/506975535).

**Comment by TaiSakuma** [comment]
* import `multiprocessing.queues` before registering a function to `atexit` https://github.com/alphatwirl/atpbar/commit/29610be852596df20b244617c188ed3816c309b3
* in addition, catch `EOFError` https://github.com/alphatwirl/atpbar/commit/672e6ab4e8bd1c76b1ffa1d17be847480cad4c8e
